### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mettoal** [JRoy/InstagramLive-PHP#157] opened 2019-05-14 15:00 UTC
hi ı have problem obs studio ( could not access the specified channel or stream key, please double-check your stream key. if it is correct, there may be a problem connecting to the server. ) do u know this problem

**Comment by itsDJDeem** [comment] 2019-05-14 15:46
Having this same issue. I've been trying to find a fix

**Comment by mahdialmasi313** [comment] 2019-05-14 16:35
Please join the issues : [https://github.com/JRoy/InstagramLive-PHP/issues/156](https://github.com/JRoy/InstagramLive-PHP/issues/156)

**Comment by JRoy** [comment] 2019-05-14 16:57
Duplicate of #156, please move discussion to there.

**Closed by JRoy** 2019-05-14 16:57 UTC
