### ISSUE TITLE
Live bug on OBS

### ISSUE THREAD

**Issue by mahdialmasi313** [JRoy/InstagramLive-PHP#156] opened 2019-05-14 12:07 UTC
We're having trouble getting started with the obs.
.
The message is this:
Could not access the specified channel or stream key, please double check your stream key it is.conect, there may be a problem connecting to the server

**Comment by JRoy** [comment] 2019-05-14 13:31
Do `php goLive.php --use-rmtps` for now

**Comment by mahdialmasi313** [comment] 2019-05-14 13:58
Thank you so much for your advice
But, It's a mistake now :
Failed to connect to server 😐

**Comment by itsDJDeem** [comment] 2019-05-14 15:51
same issue over here. is this because of instagram?

**Comment by JRoy** [comment] 2019-05-14 16:58
--use-rmtps appears to be working got now but I'll have to look into more

**Comment by ivanfeanor** [comment] 2019-05-15 10:33
--use-rmtps  works (not checked obs, working with ffmpeg)
I had to wait a little bit to get new url - it was "Recovery Detected, Restarting Stream..." - i waited a little bit more and got new server url for rtmps (rtmps://live-upload.instagram.com:443/rtmp/) - and it works.

**Comment by ivanfeanor** [comment] 2019-05-15 10:34
> Do `php goLive.php --use-rmtps` for now

probably should be default right now

**Comment by PomegranateApps** [comment] 2019-05-15 16:32
This still does not work for me. I get the same error message.

**Comment by ahmadd110** [comment] 2019-05-15 20:27
same problem!!!

**Comment by AngerKingz** [comment] 2019-05-15 20:40
wtf

**Comment by AngerKingz** [comment] 2019-05-15 20:41
its not working

**Comment by JRoy** [comment] 2019-05-15 20:44
@PomegranateApps @ahmadd110 @AngerKingz @itsDJDeem @mahdialmasi313: Please use `php goLive.php --use-rmtps` for now and **MAKE SURE TO CHANGE YOUR STREAM URL**! It's the cause of this problem and changing it with the new one provided when doing the `php goLive.php --use-rmtps` command fixes the problem.

@ivanfeanor: I am releasing 1.7 today which will default to this. It appears Facebook (and Instagram) have removed RMTP support from their backends.

**Comment by ahmadd110** [comment] 2019-05-16 12:02
Version 1.7?

**Comment by JRoy** [comment] 2019-05-16 12:33
@ahmadd110 it's an upcoming version that's in the works and I'm waiting on API changes I'm working on

**Comment by ahmadd110** [comment] 2019-05-16 13:08
I am enthusiastically.

**Comment by Luxhor** [comment] 2019-05-16 17:18
JRoy you are big Super! Waiting version 1.7

**Comment by Luxhor** [comment] 2019-05-16 17:21
rtmps://live-upload.instagram.com:443/rtmp/   works in vMIX !

**Comment by PomegranateApps** [comment] 2019-05-16 20:40
Ok, this worked for me! I was running an older version mistakenly and didn't do a composer update.

**Comment by JRoy** [comment] 2019-05-17 12:53
Fixed in 1.7

**Closed** 2019-05-17 12:54 UTC
Labels: bug

**Comment by bwflinn** [comment] 2019-05-17 13:36
I've updated to 1.7, changed my streaming url in OBS to the new rtmps and it's failing like this for me...

C:\xampp\htdocs\560_InstagramLIVE-PHP>php goLive.php --use-rtmps
Loading InstagramLive-PHP v1.7...
Logging into Instagram! Please wait as this can take up-to two minutes...
Logged In!
Recovery Detected, Restarting Stream...
**Please** update your current Stream URL if you have one in your current stream
ing program. A recent update has made the old url not work so please use the one
 below!
================================ Stream URL ================================
rtmp://live-upload.instagram.com:80/rtmp/
================================ Stream URL ================================
======================== Current Stream Key ========================
17953713217272944?s_efg=eyJxZV9ncm91cHMiOnsiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50
Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xpdmVfZW5hYmxlX2xpdmVkYXNoIjp7ImxpdmVk
YXNoX21vZGUiOiJwcmltYXJ5In0sImlnX2xpdmVfZW5hYmxlX3BvcF9wcmltaW5nIjp7ImVuYWJsZWQi
OiJ0cnVlIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6InRy
dWUifX19&s_vt=ig&a=AbycZQDD5FK2RJGM
======================== Current Stream Key ========================

**Please** update your current Stream URL if you have one in your current stream
ing program. A recent update has made the old url not work so please use the one
 below!
Command Line: Windows/macOS Detected! A new console will open for command input
and this will become command/like output.
Error While Creating Livestream: InstagramAPI\Response\BroadcastCommentsResponse
: Sorry, this media has been deleted.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.7
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#82dc3bd9f5cea10947e1f2e7cc8201938eecb39b
Operating System: WINNT
PHP Version: 7.3.4
PHP Runtime: cli
PHP Binary: C:\xampp\php\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
Exception: InstagramAPI\Response\BroadcastCommentsResponse: Sorry, this media ha
s been deleted.
============END DUMP============

**Comment by ahmadd110** [comment] 2019-05-18 12:22
Don't use --use-rtmps for v1.7

**Comment by bwflinn** [comment] 2019-05-20 11:46
I have also ran without --use-rtmps and got the following:

C:\xampp\htdocs\560_InstagramLIVE-PHP>php goLive.php
Loading InstagramLive-PHP v1.7...
Logging into Instagram! Please wait as this can take up-to two minutes...
Logged In!
Recovery Detected, Restarting Stream...
**Please** update your current Stream URL if you have one in your current stream
ing program. A recent update has made the old url not work so please use the one
 below!
================================ Stream URL ================================
rtmp://live-upload.instagram.com:80/rtmp/
================================ Stream URL ================================
======================== Current Stream Key ========================
17953713217272944?s_efg=eyJxZV9ncm91cHMiOnsiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50
Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xpdmVfZW5hYmxlX2xpdmVkYXNoIjp7ImxpdmVk
YXNoX21vZGUiOiJwcmltYXJ5In0sImlnX2xpdmVfZW5hYmxlX3BvcF9wcmltaW5nIjp7ImVuYWJsZWQi
OiJ0cnVlIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6InRy
dWUifX19&s_vt=ig&a=AbycZQDD5FK2RJGM
======================== Current Stream Key ========================

**Please** update your current Stream URL if you have one in your current stream
ing program. A recent update has made the old url not work so please use the one
 below!
Command Line: Windows/macOS Detected! A new console will open for command input
and this will become command/like output.
Error While Creating Livestream: InstagramAPI\Response\BroadcastCommentsResponse
: Sorry, this media has been deleted.
===========BEGIN DUMP===========
InstagramLive-PHP Version: 1.7
InstagramLive-PHP Flavor: stable
Instagram-API Version: dev-master#82dc3bd9f5cea10947e1f2e7cc8201938eecb39b
Operating System: WINNT
PHP Version: 7.3.4
PHP Runtime: cli
PHP Binary: C:\xampp\php\php.exe
Bypassing OS-Check: false
Composer Lock: true
Vendor Folder: true
Exception: InstagramAPI\Response\BroadcastCommentsResponse: Sorry, this media ha
s been deleted.
============END DUMP============

**Comment by forushorus** [comment] 2019-05-20 15:22
I cannot go live. its says that in the obs could not connect to server. This is what it says on my cmd


D:\Documents\igLive>php goLive.php
Loading InstagramLive-PHP v1.7...
Logging into Instagram! Please wait as this can take up-to two minutes...
Logged In!
Creating Livestream...
OBS Integration: OBS was not detected, disabling! Please make a ticket on GitHub if you have OBS installed.
**Please** update your current Stream URL if you have one in your current streaming program. A recent update has made the old url not work so please use the one below!
================================ Stream URL ================================
rtmps://live-upload.instagram.com:443/rtmp/
================================ Stream URL ================================
======================== Current Stream Key ========================
18040705153082573?s_efg=eyJxZV9ncm91cHMiOnsiaWdfZmJsaXZlX3NlcnZlcl9leHBlcmltZW50Ijp7InNlcnZpY2VfcG9ydCI6IjE3MDAwIn0sImlnX2xpdmVfZW5hYmxlX2xpdmVkYXNoIjp7ImxpdmVkYXNoX21vZGUiOiJwcmltYXJ5In0sImlnX2xpdmVfZW5hYmxlX3BvcF9wcmltaW5nIjp7ImVuYWJsZWQiOiJ0cnVlIn0sImlnX2xvd19sYXRlbmN5X3Byb2R1Y3Rpb25fdW5pdmVyc2UiOnsiZW5hYmxlZCI6InRydWUifX19&s_vt=ig&a=AbxyOCUQcghx5F7X
======================== Current Stream Key ========================

**Please** update your current Stream URL if you have one in your current streaming program. A recent update has made the old url not work so please use the one below!
Windows: Your stream key has been pre-copied to your clipboard.
Please  start streaming to the url and key above! Once you are live, please press enter!
